---
title: Lerntagebuch
tagline: als Leistungsnachweis für das Modul BAIN
description: Für das Modul Bibliotheks- und Archivinformatik an der FH Graubünden führe ich dieses Lerntagebuch. Viel Spass beim Stöbern
url: 
baseurl: '/lerntagebuch-bain'
author:
  name: rumolin
  url: https://github.com/rumolin
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''

theme: jekyll-theme-hydeout
